import { ITraineeInfo } from "./src/types";

export const traineesData: ITraineeInfo[] = [
  {
    "name": "ARCTIC",
    "nickname": "ARCTIC",
    "subheading": "I will bring happiness with my bright energy!",
    "birthday": "2008.10.09",
    "height": 173.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6836cfeef7d8031d1b9fcea0?hl=en",
    "imagefile": "1.jpg",
    "agency": "IST ENTERTAINMENT",
    "hobby": "Listening to songs, taking walks, meditating",
    "specialty": "Finger tricks, flexibility",
    "name1": "Arctic",
    "kc_name": "아틱",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 36.0,
    "ep2": 31.0,
    "star_rank2": 1.0,
    "ep3_master": 66.0,
    "ep3": 50.0,
    "ep5": 45.0,
    "star_rank5": 2,
    "ep7":19,
    "star_rank7": 3,
    "ep8": 33,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8

  },
  {
    "name": "CHEN BO WEN",
    "nickname": "CHEN BO WEN",
    "subheading": "If it’s something I want, I will do my best to get it",
    "birthday": "2008.02.01",
    "height": 170.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684147451231526cb88a3ef9?hl=en",
    "imagefile": "2.jpg",
    "agency": "Individual",
    "hobby": "Singing, dancing, skiing",
    "specialty": "Body wave, acting cute",
    "name1": "Chen Bo wen",
    "kc_name": "陈博文",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 36.0,
    "ep2": 16.0,
    "star_rank2": 3.0,
    "ep3_master": 18.0,
    "ep3": 27.0,
    "ep5": 32,
    "star_rank5": 2,
    "ep7":47,
    "star_rank7": 2,
    "ep8": 44,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "CHEN KAI WEN",
    "nickname": "CHEN KAI WEN",
    "subheading": "I am KAI WEN, who embraces every challenge with enthusiasm",
    "birthday": "2005.12.19",
    "height": 182.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684147d8a0dc83489d60dfe6?hl=en",
    "imagefile": "3.jpg",
    "agency": "CHROMOSOME",
    "hobby": "Listening to music, playing games, playing with cats, role-playing mystery game",
    "specialty": "Choreographing, magic",
    "name1": "Chen Kai wen",
    "kc_name": "陈凯文",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 8.0,
    "ep2": 6.0,
    "star_rank2": 1.0,
    "ep3_master": 68.0,
    "ep3": 18.0,
    "ep5": 21,
    "star_rank5": 3,
    "ep7": 16,
    "star_rank7": 3,
    "ep8": 18,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "CHUEI LI YU",
    "nickname": "CHUEI LI YU",
    "subheading": "I will take my first step toward becoming a superstar through BOYS II PLANET!",
    "birthday": "2004.01.02",
    "height": 180.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d3d2602a1935e6d416fe6?hl=en",
    "imagefile": "4.jpg",
    "agency": "FNC ENTERTAINMENT",
    "hobby": "Listening to music, taking pictures, taking walks",
    "specialty": "Drawing",
    "name1": "Chuei Li yu",
    "kc_name": "최립우",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 4.0,
    "ep2": 4.0,
    "star_rank2": 1.0,
    "ep3_master": 55.0,
    "ep3": 3.0,
    "ep5": 6,
    "star_rank5": 3,
    "ep7": 26,
    "star_rank7": 2,
    "ep8": 10,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "CHUNG SANG HYEON",
    "nickname": "CHUNG SANG HYEON",
    "subheading": "I will rise to become your all-time number one!",
    "birthday": "2007.09.19",
    "height": 178.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d33f7ff18bf5bf51996d6?hl=en",
    "imagefile": "5.jpg",
    "agency": "WAKEONE",
    "hobby": "Collecting figures, writing rap lyrics",
    "specialty": "Communicating with animals, training cats",
    "name1": "Chung Sang hyeon",
    "kc_name": "정상현",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 3.0,
    "ep2": 6.0,
    "star_rank2": 1.0,
    "ep3_master": 58.0,
    "ep3": 4.0,
    "ep5": 3,
    "star_rank5": 3,
    "ep7": 18,
    "star_rank7": 3,
    "ep8": 6,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "DANG HONG HAI",
    "nickname": "DANG HONG HAI",
    "subheading": "I will be the highlight of BOYS II PLANET!",
    "birthday": "2003.10.26",
    "height": 181.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6840f9cac6c1623a33cc2a64?hl=en",
    "imagefile": "6.jpg",
    "agency": "DONGYO ENTERTAINMENT",
    "hobby": "Watching the news, taking walks, studying languages, living healthily",
    "specialty": "Foreign languages (Chinese/Korean/English), face & proportions",
    "name1": "Dang Hong Hai",
    "kc_name": "Đặng Hồng Hải",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 13.0,
    "ep2": 17.0,
    "star_rank2": 2.0,
    "ep3_master": 28.0,
    "ep3": 25.0,
    "ep5": 30,
    "star_rank5": 2,
    "ep7": 21,
    "star_rank7": 2,
    "ep8": 46,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "FAN ZHE YI",
    "nickname": "FAN ZHE YI",
    "subheading": "The phrase “If only I had…” does not exist in my dictionary!",
    "birthday": "2006.01.22",
    "height": 188.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684148b61231526cb88a3efa?hl=en",
    "imagefile": "7.jpg",
    "agency": "Individual",
    "hobby": "Taking photos, fashion styling, traveling, acting",
    "specialty": "Cooking, striking 10 poses in 10 seconds",
    "name1": "Fan Zhe yi",
    "kc_name": "范哲逸",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 3.0,
    "ep2": 2.0,
    "star_rank2": 1.0,
    "ep3_master": 59.0,
    "ep3": 11.0,
    "ep5": 13,
    "star_rank5": 3,
    "ep7": 35,
    "star_rank7": 3,
    "ep8": 25,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "HAN HARRY JUNE",
    "nickname": "HAN HARRY JUNE",
    "subheading": "I’m aiming for first place",
    "birthday": "2004.01.01",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d406632363472da8ee11d?hl=en",
    "imagefile": "8.jpg",
    "agency": "BRAVE ENTERTAINMENT",
    "hobby": "Taking dance classes, creating choreography,playing basketball, riding a bike while listening to music",
    "specialty": "Creating choreography, playing basketball, falling asleep within 3 seconds of lying down",
    "name1": "Han Harry June",
    "kc_name": "한해리준",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 33.0,
    "ep2": 34.0,
    "star_rank2": 2.0,
    "ep3_master": 26.0,
    "ep3": 47.0,
    "ep5": 47,
    "star_rank5": 2,
    "ep7": 22,
    "star_rank7": 2,
    "ep8": 26,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "HE XIN LONG",
    "nickname": "HE XIN LONG",
    "subheading": "I will do my best!",
    "birthday": "2005.03.11",
    "height": 177.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6841494379ae5728aa69a608?hl=en",
    "imagefile": "9.jpg",
    "agency": "NCC ENTERTAINMENT",
    "hobby": "Listening to music",
    "specialty": "Choreographing",
    "name1": "He Xin long",
    "kc_name": "贺鑫隆",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 14.0,
    "ep2": 15.0,
    "star_rank2": 3.0,
    "ep3_master": 16.0,
    "ep3": 15.0,
    "ep5": 9,
    "star_rank5": 3,
    "ep7": 9,
    "star_rank7": 3,
    "ep8": 4,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "HE ZHONG XING",
    "nickname": "HE ZHONG XING",
    "subheading": "The stars of a midsummer night will surely shine brightly!",
    "birthday": "2003.08.08",
    "height": 185.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68414990d3b30c641daf8d53?hl=en",
    "imagefile": "10.jpg",
    "agency": "Individual",
    "hobby": "Studying stage performances",
    "specialty": "Striking poses",
    "name1": "He Zhong xing",
    "kc_name": "贺仲星",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 17.0,
    "ep2": 19.0,
    "star_rank2": 1.0,
    "ep3_master": 70.0,
    "ep3": 32.0,
    "ep5": 36,
    "star_rank5": 2,
    "ep7": 24,
    "star_rank7": 3,
    "ep8": 29,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "HSU CHING YU",
    "nickname": "HSU CHING YU",
    "subheading": "I’ll perform without regrets—showing you my coolest and cutest sides on stage!",
    "birthday": "2009.08.31",
    "height": 174.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68397caed0379713d48a9877?hl=en",
    "imagefile": "11.jpg",
    "agency": "WAKEONE",
    "hobby": "Doing laundry, shopping, dancing",
    "specialty": "Composing music, writing lyrics, creating choreography",
    "name1": "Hsu Ching yu",
    "kc_name": "쉬칭위",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 24.0,
    "ep2": 10.0,
    "star_rank2": 3.0,
    "ep3_master": 9.0,
    "ep3": 13.0,
    "ep5": 14,
    "star_rank5": 3,
    "ep7": 33,
    "star_rank7": 2,
    "ep8": 21,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "HU HAN WEN",
    "nickname": "HU HAN WEN",
    "subheading": "I believe every drop of sweat I’ve shed was for this moment. Now, I’ll try become a ray of light on stage that shines on you, and a flower that never fades!",
    "birthday": "2000.12.19",
    "height": 180.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68414a0e7e0c946a7370e4e7?hl=en",
    "imagefile": "12.jpg",
    "agency": "Individual",
    "hobby": "Eating meals, exercising, dancing, playing games",
    "specialty": "Strong stamina and strength",
    "name1": "Hu Han wen",
    "kc_name": "胡瀚文",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 11.0,
    "ep2": 14.0,
    "star_rank2": 1.0,
    "ep3_master": 62.0,
    "ep3": 26.0,
    "ep5": 25,
    "star_rank5": 2,
    "ep7": 25,
    "star_rank7": 3,
    "ep8": 23,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "JANG HAN EUM",
    "nickname": "JANG HAN EUM",
    "subheading": "I’ll strive for perfection and prove it with results.",
    "birthday": "2004.12.21",
    "height": 183.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d2e1d62e19e064eec8507?hl=en",
    "imagefile": "13.jpg",
    "agency": "ES NATION",
    "hobby": "Listening to music, lying down and resting, playing with pets",
    "specialty": "Vocals, zoning out",
    "name1": "Jang Han eum",
    "kc_name": "장한음",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 12.0,
    "ep2": 17.0,
    "star_rank2": 1.0,
    "ep3_master": 53.0,
    "ep3": 19.0,
    "ep5": 12,
    "star_rank5": 3,
    "ep7": 1,
    "star_rank7": 3,
    "ep8": 14,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "JO GYE HYEON",
    "nickname": "JO GYE HYEON",
    "subheading": "I aim to shine brighter than anyone else on stage!",
    "birthday": "1999.05.14",
    "height": 177.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d3c2882e7fe5cb16ec55d?hl=en",
    "imagefile": "14.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Lying down, watching animations and variety shows,singing songs",
    "specialty": "Singing, dancing",
    "name1": "Jo Gye hyeon",
    "kc_name": "조계현",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 19.0,
    "ep2": 20.0,
    "star_rank2": 3.0,
    "ep3_master": 14.0,
    "ep3": 40.0,
    "ep5": 40,
    "star_rank5": 2,
    "ep7": 10,
    "star_rank7": 3,
    "ep8": 37,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "JUN LEE JEONG",
    "nickname": "JUN LEE JEONG",
    "subheading": "No matter how distant the dream, I won’t give up.",
    "birthday": "2003.09.08",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d3266f334731f5283e9bf?hl=en",
    "imagefile": "15.jpg",
    "agency": "CJes Studios",
    "hobby": "Composing music, collecting good lines from movies, reading",
    "specialty": "Composing music, creating choreography, playing guitar",
    "name1": "Jun Lee jeong",
    "kc_name": "전이정",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 18.0,
    "ep2": 24.0,
    "star_rank2": 1.0,
    "ep3_master": 49.0,
    "ep3": 34.0,
    "ep5": 23,
    "star_rank5": 3,
    "ep7": 5,
    "star_rank7": 3,
    "ep8": 12,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "JUNG HYUN JUN",
    "nickname": "JUNG HYUN JUN",
    "subheading": "With unwavering passion, I’ll grow step by step. Let’s create our brightest planet together—go for it!",
    "birthday": "2009.03.13",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d3b4b2df59069b98136f3?hl=en",
    "imagefile": "16.jpg",
    "agency": "NOUER ENTERTAINMENT",
    "hobby": "Playing Animal Crossing",
    "specialty": "Equipped with bright energy! (When you see my passion on stage, you will automatically smile! 😊)",
    "name1": "Jung Hyun jun",
    "kc_name": "정현준",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 41.0,
    "ep2": 47.0,
    "star_rank2": 3.0,
    "ep3_master": 7.0,
    "ep3": 42.0,
    "ep5": 41,
    "star_rank5": 2,
    "ep7": 23,
    "star_rank7": 3,
    "ep8": 47,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "KANG WOO JIN",
    "nickname": "KANG WOO JIN",
    "subheading": "I’ll keep going until the day I become your No. 1 star!!",
    "birthday": "2007.06.07",
    "height": 184.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6836d98cb12f8f5047c2d8fb?hl=en",
    "imagefile": "17.jpg",
    "agency": "Individual",
    "hobby": "Writing, tasting chocolates from around the world",
    "specialty": "Playing guitar, composing music, playing baseball",
    "name1": "Kang Woo jin",
    "kc_name": "강우진",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 25.0,
    "ep2": 5.0,
    "star_rank2": 1.0,
    "ep3_master": 61.0,
    "ep3": 9.0,
    "ep5": 10,
    "star_rank5": 3,
    "ep7": 45,
    "star_rank7": 2,
    "ep8": 16,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "KIM DONG YUN",
    "nickname": "KIM DONG YUN",
    "subheading": "There’s more to my charm than you’ve seen—I’ll show you it all~!!!",
    "birthday": "2002.02.18",
    "height": 177.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837b3921ce69a5b2c4d53ab?hl=en",
    "imagefile": "18.jpg",
    "agency": "Woollim ENTERTAINMENT",
    "hobby": "Playing soccer, taking walks,massaging with a massage ball, drinking Americano with an added shot",
    "specialty": "Playing soccer, shooting, identifying the song title after hearing just the first 0.1 second",
    "name1": "Kim Dong yun",
    "kc_name": "김동윤",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 14.0,
    "ep2": 22.0,
    "star_rank2": 2.0,
    "ep3_master": 39.0,
    "ep3": 38.0,
    "ep5": 37,
    "star_rank5": 2,
    "ep7": 12,
    "star_rank7": 2,
    "ep8": 43,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "KIM GEON WOO",
    "nickname": "KIM GEON WOO",
    "subheading": "I won’t miss this opportunity. I’ll give my all every moment.",
    "birthday": "2003.04.11",
    "height": 183.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6836ddef74902b1be6ccf2ac?hl=en",
    "imagefile": "19.jpg",
    "agency": "Individual",
    "hobby": "Playing soccer and baseball, traveling, watching classical performances",
    "specialty": "Playing piano, absolute pitch",
    "name1": "Kim Geon woo",
    "kc_name": "김건우",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 7.0,
    "ep2": 9.0,
    "star_rank2": 3.0,
    "ep3_master": 5.0,
    "ep3": 17.0,
    "ep5": 16,
    "star_rank5": 3,
    "ep7": 11,
    "star_rank7": 3,
    "ep8": 7,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "KIM IN HU",
    "nickname": "KIM IN HU",
    "subheading": "Believing this is my first and last chance, I’ll give it everything I’ve got!",
    "birthday": "2005.01.22",
    "height": 176.3,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837bd148af5b9434f96054c?hl=en",
    "imagefile": "20.jpg",
    "agency": "BIG PLANET MADE ENTERTAINMENT",
    "hobby": "Going on gourmet tours, taking walks, playing games, watching movies, shopping",
    "specialty": "Spongebob voice impression, working hard at anything, \nself-questioning, providing irrelevant answers to questions",
    "name1": "Kim In hu",
    "kc_name": "김인후",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 34.0,
    "ep2": 39.0,
    "star_rank2": 3.0,
    "ep3_master": 23.0,
    "ep3": 54.0,
    "ep5": 44,
    "star_rank5": 2,
    "ep7": 46,
    "star_rank7": 2,
    "ep8": 36,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "KIM JAE HYUN",
    "nickname": "KIM JAE HYUN",
    "subheading": "Hello, I’m “JAE HYUN,” and I’ll \"reproduce (jae-hyun in Korean)\" the best stage right here!",
    "birthday": "2010.01.03",
    "height": 173.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837bf765c79d84f56b22c30?hl=en",
    "imagefile": "21.jpg",
    "agency": "CUBE ENTERTAINMENT",
    "hobby": "Shopping, listening to songs, watching romance dramas",
    "specialty": "Playing soccer, songwriting, composing music, speaking calmly",
    "name1": "Kim Jae hyun",
    "kc_name": "김재현",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 54.0,
    "ep2": 18.0,
    "star_rank2": 1.0,
    "ep3_master": 50.0,
    "ep3": 31.0,
    "ep5": 33,
    "star_rank5": 2,
    "ep7": 3,
    "star_rank7": 3,
    "ep8": 27,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "KIM JUN MIN",
    "nickname": "KIM JUN MIN",
    "subheading": "Watch me once, and you’ll want to see me again and again!",
    "birthday": "2002.12.31",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837c0b672e9bb5e3f1a574a?hl=en",
    "imagefile": "22.jpg",
    "agency": "CJes Studios",
    "hobby": "Dancing, shopping, watching movies",
    "specialty": "Writing lyrics",
    "name1": "Kim Jun min",
    "kc_name": "김준민",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 17.0,
    "ep2": 21.0,
    "star_rank2": 3.0,
    "ep3_master": 15.0,
    "ep3": 36.0,
    "ep5": 27,
    "star_rank5": 2,
    "ep7": 20,
    "star_rank7": 3,
    "ep8": 11,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "KIM JUN SEO",
    "nickname": "KIM JUN SEO",
    "subheading": "Every stage is my last—I’ll give it my all, so please support me!",
    "birthday": "2001.11.20",
    "height": 178.7,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837c22d266f2842f3e62c18?hl=en",
    "imagefile": "23.jpg",
    "agency": "OUI ENTERTAINMENT",
    "hobby": "Shopping for base products, doing aerobic exercise (biking), staying hydrated by drinking plenty of water",
    "specialty": "Acting, taking pretty pictures, giving motivating words to fans",
    "name1": "Kim Jun seo",
    "kc_name": "김준서",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 8.0,
    "ep2": 8.0,
    "star_rank2": 3.0,
    "ep3_master": 10.0,
    "ep3": 6.0,
    "ep5": 4,
    "star_rank5": 3,
    "ep7": 13,
    "star_rank7": 3,
    "ep8": 5,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "KIM SI HWAN",
    "nickname": "KIM SI HWAN",
    "subheading": "Star Creators—are you ready to fall for me?",
    "birthday": "2005.11.28",
    "height": 179.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837b5805c79d84f56b22c2f?hl=en",
    "imagefile": "24.jpg",
    "agency": "IST ENTERTAINMENT",
    "hobby": "Playing games, exploring unfamiliar places, ocean swimming, singing, listening to music, gaming, and working out",
    "specialty": "Art (immitating drawings), long-distance running, doing nothing",
    "name1": "Kim Si hwan",
    "kc_name": "김시환",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 27.0,
    "ep2": 29.0,
    "star_rank2": 3.0,
    "ep3_master": 20.0,
    "ep3": 46.0,
    "ep5": 43,
    "star_rank5": 2,
    "ep7": 42,
    "star_rank7": 2,
    "ep8": 48,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "KIM TAE JO",
    "nickname": "KIM TAE JO",
    "subheading": "My path is clear. I’ll move forward, undeterred by any challenge. If you like me, please support KIM TAE JO!",
    "birthday": "2010.07.01",
    "height": 181.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837c44e179257342956ed48?hl=en",
    "imagefile": "25.jpg",
    "agency": "ChoCo ENTERTAINMENT",
    "hobby": "Playing soccer and PlayStation games, making beats,\ndigging for trendy music, broadcasting while eating trendy food",
    "specialty": "DJing, playing electric guitar, making beats in 1 minute, locking dance",
    "name1": "Kim Tae jo",
    "kc_name": "김태조",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 53.0,
    "ep2": 25.0,
    "star_rank2": 3.0,
    "ep3_master": 22.0,
    "ep3": 39.0,
    "ep5": 42,
    "star_rank5": 2,
    "ep7": 29,
    "star_rank7": 2,
    "ep8": 45,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "LEE LEO",
    "nickname": "LEE LEO",
    "subheading": "I will debut!!",
    "birthday": "2002.08.22",
    "height": 179.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d082b9d605a41583cecec?hl=en",
    "imagefile": "26.jpg",
    "agency": "GRID ENTERTAINMENT",
    "hobby": "Watching media, searching for delicious dessert restaurants",
    "specialty": "Composing music",
    "name1": "Lee Leo",
    "kc_name": "이리오",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 5.0,
    "ep2": 2.0,
    "star_rank2": 3.0,
    "ep3_master": 6.0,
    "ep3": 5.0,
    "ep5": 5,
    "star_rank5": 3,
    "ep7": 43,
    "star_rank7": 2,
    "ep8": 3,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "LEE SANG WON",
    "nickname": "LEE SANG WON",
    "subheading": "I will always strive for the best",
    "birthday": "2003.05.08",
    "height": 177.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d0aeb32363472da8ee11a?hl=en",
    "imagefile": "27.jpg",
    "agency": "GRID ENTERTAINMENT",
    "hobby": "Digging for music, watching mukbang",
    "specialty": "DJing",
    "name1": "Lee Sang won",
    "kc_name": "이상원",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 1.0,
    "ep2": 1.0,
    "star_rank2": 3.0,
    "ep3_master": 2.0,
    "ep3": 1.0,
    "ep5": 1,
    "star_rank5": 3,
    "ep7": 6,
    "star_rank7": 3,
    "ep8": 1,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "LI ZI HAO",
    "nickname": "LI ZI HAO",
    "subheading": "BOYS II PLANET, wait for me - I’m coming!",
    "birthday": "2004.10.22",
    "height": 176.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684116b2920f852810393460?hl=en",
    "imagefile": "28.jpg",
    "agency": "NCC ENTERTAINMENT",
    "hobby": "Singing, dancing, rap, playing games, composition",
    "specialty": "Freestyle dance, girl group dance",
    "name1": "Li Zi hao",
    "kc_name": "李梓豪",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 16.0,
    "ep2": 22.0,
    "star_rank2": 2.0,
    "ep3_master": 47.0,
    "ep3": 37.0,
    "ep5": 31,
    "star_rank5": 2,
    "ep7": 27,
    "star_rank7": 2,
    "ep8": 17,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "MASATO",
    "nickname": "MASATO",
    "subheading": "I won’t waste a single moment. I’ll give my all on every stage!",
    "birthday": "2003.09.21",
    "height": 171.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68396af2ff963d45bc7c6686?hl=en",
    "imagefile": "29.jpg",
    "agency": "iNKODE ENTERTAINMENT",
    "hobby": "Watching animations, taking walks, appreciating nature",
    "specialty": "Playing table tennis, performing magic tricks, swimming, playing soccer",
    "name1": "Masato",
    "kc_name": "마사토",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 6.0,
    "ep2": 7.0,
    "star_rank2": 2.0,
    "ep3_master": 34.0,
    "ep3": 8.0,
    "ep5": 8,
    "star_rank5": 3,
    "ep7": 32,
    "star_rank7": 2,
    "ep8": 9,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "NA YUN SEO",
    "nickname": "NA YUN SEO",
    "subheading": "I will be your best choice!",
    "birthday": "2010.01.24",
    "height": 170.7,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837dfcd266f2842f3e62c19?hl=en",
    "imagefile": "30.jpg",
    "agency": "CUBE ENTERTAINMENT",
    "hobby": "Skateboarding, playing soccer, playing soccer games",
    "specialty": "Dancing, creating choreography, vocals, skateboarding",
    "name1": "Na Yun seo",
    "kc_name": "나윤서",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 39.0,
    "ep2": 19.0,
    "star_rank2": 3.0,
    "ep3_master": 12.0,
    "ep3": 29.0,
    "ep5": 22.0,
    "star_rank5": 3,
    "ep7": 4,
    "star_rank7": 3,
    "ep8": 20,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "NIAN BO HENG",
    "nickname": "NIAN BO HENG",
    "subheading": "I will draw you into the depths of NIAN’s deep voice",
    "birthday": "2006.01.06",
    "height": 181.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6840f860746e21370e0a9685?hl=en",
    "imagefile": "31.jpg",
    "agency": "BILL ENTERTAINMENT",
    "hobby": "Rapping, playing games, badminton",
    "specialty": "Rapping fast, beatboxing, trilingual (Korean/English/Chinese)",
    "name1": "Nian Bo heng",
    "kc_name": "年博恒",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 57.0,
    "ep2": 13.0,
    "star_rank2": 3.0,
    "ep3_master": 17.0,
    "ep3": 24.0,
    "ep5": 24,
    "star_rank5": 3,
    "ep7": 44,
    "star_rank7": 2,
    "ep8": 31,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "PARK DONG GYU",
    "nickname": "PARK DONG GYU",
    "subheading": "I’ve trained for a long time, and I’ll show you the solid skills I’ve built!",
    "birthday": "2005.03.16",
    "height": 182.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837eab9cbda8e7e840d2708?hl=en",
    "imagefile": "32.jpg",
    "agency": "IST ENTERTAINMENT",
    "hobby": "Going to cafes and watching people, riding a bike to work",
    "specialty": "Performing leg fighting",
    "name1": "Park Dong gyu",
    "kc_name": "박동규",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 28.0,
    "ep2": 14.0,
    "star_rank2": 3.0,
    "ep3_master": 11.0,
    "ep3": 30.0,
    "ep5": 29,
    "star_rank5": 2,
    "ep7": 14,
    "star_rank7": 3,
    "ep8": 24,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "PARK JUN IL",
    "nickname": "PARK JUN IL",
    "subheading": "I’ll do my best to show you everything I’ve got!",
    "birthday": "2004.04.05",
    "height": 171.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837ed25631cff460ffce514?hl=en",
    "imagefile": "33.jpg",
    "agency": "iNKODE ENTERTAINMENT",
    "hobby": "Taking walks, window shopping, exploring dessert restaurants",
    "specialty": "Practicing Taekwondo, performing acrobatics",
    "name1": "Park Jun il",
    "kc_name": "박준일",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 13.0,
    "ep2": 16.0,
    "star_rank2": 2.0,
    "ep3_master": 44.0,
    "ep3": 33.0,
    "ep5": 35,
    "star_rank5": 2,
    "ep7": 7,
    "star_rank7": 3,
    "ep8": 13,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "PENG JIN YU",
    "nickname": "PENG JIN YU",
    "subheading": "With 1000% effort, I will run toward my dream. I believe that if there is a will, there is a way!",
    "birthday": "2006.03.10",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684148dacb7dda777b2e2d31?hl=en",
    "imagefile": "34.jpg",
    "agency": "Individual",
    "hobby": "Exercising, eating delicious food, watching dramas",
    "specialty": "Strong will, excellent language learning ability (can speak a little French, fluent in English, studying Korean!)",
    "name1": "Peng Jin yu",
    "kc_name": "彭锦煜",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 6.0,
    "ep2": 9.0,
    "star_rank2": 1.0,
    "ep3_master": 63.0,
    "ep3": 22.0,
    "ep5": 28,
    "star_rank5": 2,
    "ep7": 37,
    "star_rank7": 2,
    "ep8": 41,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "SEN",
    "nickname": "SEN",
    "subheading": "From beginning to end, I am grateful to everyone and will become the brightest idol!",
    "birthday": "2005.12.25",
    "height": 170.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68411e755a617c7dfa2bb1c2?hl=en",
    "imagefile": "35.jpg",
    "agency": "iNKODE",
    "hobby": "Drawing, enjoying nature, handwriting, strength training",
    "specialty": "Skateboarding, acrobatics, standing double jump",
    "name1": "Sen",
    "kc_name": "센",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 30.0,
    "ep2": 11.0,
    "star_rank2": 2.0,
    "ep3_master": 45.0,
    "ep3": 23.0,
    "ep5": 26,
    "star_rank5": 2,
    "ep7": 40,
    "star_rank7": 2,
    "ep8": 32,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "SEO WON",
    "nickname": "SEO WON",
    "subheading": "I’ve taken a big step to become a star. Please join me on this journey! Let’s chase our dreams together—please show lots of love. 🩵🩵🩵🩵",
    "birthday": "2000.12.18",
    "height": 170.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683976e2956766128aa80fb0?hl=en",
    "imagefile": "36.jpg",
    "agency": "Individual",
    "hobby": "Window shopping, climbing, taking walks",
    "specialty": "Self-makeup, calligraphy, girl group dancing",
    "name1": "Seo Won",
    "kc_name": "서원",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 9.0,
    "ep2": 12.0,
    "star_rank2": 3.0,
    "ep3_master": 19.0,
    "ep3": 20.0,
    "ep5": 20,
    "star_rank5": 3,
    "ep7": 38,
    "star_rank7": 2,
    "ep8": 39,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "SUN HENG YU",
    "nickname": "SUN HENG YU",
    "subheading": "I will set my whole body on fire for debut!",
    "birthday": "2001.06.22",
    "height": 177.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68412c3b09da8c4d959e9632?hl=en",
    "imagefile": "37.jpg",
    "agency": "Individual",
    "hobby": "Bowling, singing, playing games",
    "specialty": "Cooking, Korean language",
    "name1": "Sun Heng yu",
    "kc_name": "孙亨裕",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 53.0,
    "ep2": 4.0,
    "star_rank2": 2.0,
    "ep3_master": 25.0,
    "ep3": 10.0,
    "ep5": 11,
    "star_rank5": 3,
    "ep7": 31,
    "star_rank7": 3,
    "ep8": 15,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "SUN JIA YANG",
    "nickname": "SUN JIA YANG",
    "subheading": "Let’s all become better versions of ourselves together!",
    "birthday": "2006.01.05",
    "height": 172.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6841293b7b61ef5510b8eb9b?hl=en",
    "imagefile": "38.jpg",
    "agency": "Hangzhou Time Flowing Culture and Entertainment",
    "hobby": "Dancing, drawing",
    "specialty": "Playing piano",
    "name1": "Sun Jia yang",
    "kc_name": "孙佳洋",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 5.0,
    "ep2": 3.0,
    "star_rank2": 1.0,
    "ep3_master": 60.0,
    "ep3": 12.0,
    "ep5": 15,
    "star_rank5": 3,
    "ep7": 34,
    "star_rank7": 2,
    "ep8": 35,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "TATSUKI",
    "nickname": "TATSUKI",
    "subheading": "I won’t disappoint—I'm your cheat key on stage! Please choose TATSUKI!",
    "birthday": "2009.01.26",
    "height": 170.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d3fd9b07fc83ed869123d?hl=en",
    "imagefile": "39.jpg",
    "agency": "WAKEONE",
    "hobby": "Practicing calligraphy, studying Korean four-character idioms, writing",
    "specialty": "Swimming, eating 5 meals a day, eating 5 bowls of rice per meal",
    "name1": "Tatsuki",
    "kc_name": "타츠키",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 15.0,
    "ep2": 23.0,
    "star_rank2": 2.0,
    "ep3_master": 33.0,
    "ep3": 41.0,
    "ep5": 38,
    "star_rank5": 2,
    "ep7": 30,
    "star_rank7": 2,
    "ep8": 38,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "XUE SU REN",
    "nickname": "XUE SU REN",
    "subheading": "I will seize this opportunity! I will do my best",
    "birthday": "2004.11.09",
    "height": 181.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6841219cb3c476154e980afe?hl=en",
    "imagefile": "40.jpg",
    "agency": "Individual",
    "hobby": "Dancing, singing, choreographing",
    "specialty": "Choreography creation, voice impression",
    "name1": "Xue Su ren",
    "kc_name": "薛苏仁",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 29.0,
    "ep2": 32.0,
    "star_rank2": 2.0,
    "ep3_master": 30.0,
    "ep3": 51.0,
    "ep5": 46,
    "star_rank5": 2,
    "ep7": 36,
    "star_rank7": 2,
    "ep8": 28,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "YEOM YE CHAN",
    "nickname": "YEOM YE CHAN",
    "subheading": "I’m confident I’ll stand out no matter who’s beside me. \nI’ll make you remember only me!!",
    "birthday": "2008.09.04",
    "height": 179.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683cfb1762e19e064eec8506?hl=en",
    "imagefile": "41.jpg",
    "agency": "ChoCo ENTERTAINMENT",
    "hobby": "Creating original songs, listening to music, snacking on junk food, researching favorite artists, listening to music while showering",
    "specialty": "Eating sour food, holding back laughter, girl group dancing, freestyle dance, writing lyrics and rapping in 1 minute",
    "name1": "Yeom Ye chan",
    "kc_name": "염예찬",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 31.0,
    "ep2": 15.0,
    "star_rank2": 2.0,
    "ep3_master": 40.0,
    "ep3": 35.0,
    "ep5": 39,
    "star_rank5": 2,
    "ep7": 2,
    "star_rank7": 3,
    "ep8": 40,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "YI CHEN",
    "nickname": "YI CHEN",
    "subheading": "I have run this far with a stronger will than anyone. Please let me debut on BOYS II PLANET!! I will become a star that shines brighter than anyone!",
    "birthday": "1998.09.24",
    "height": 176.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684141bd02c5b7121f64db2b?hl=en",
    "imagefile": "42.jpg",
    "agency": "WAKEONE",
    "hobby": "Biking, hiking, exercising",
    "specialty": "B-boying, back tumbling",
    "name1": "Yi Chen",
    "kc_name": "亦辰",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 4.0,
    "ep2": 7.0,
    "star_rank2": 1.0,
    "ep3_master": 80.0,
    "ep3": 21.0,
    "ep5": 19,
    "star_rank5": 3,
    "ep7": 17,
    "star_rank7": 2,
    "ep8": 42,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "YOO KANG MIN",
    "nickname": "YOO KANG MIN",
    "subheading": "I treasure each and every day. I’ll give my all on every stage.",
    "birthday": "2003.01.25",
    "height": 174.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683cfde8f334731f5283e9bc?hl=en",
    "imagefile": "43.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Listening to songs, playing futsal, watching soccer, \nwatching movies and dramas",
    "specialty": "Imitating Conan, doing double-unders with a jump rope",
    "name1": "Yoo Kang min",
    "kc_name": "유강민",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 2.0,
    "ep2": 3.0,
    "star_rank2": 3.0,
    "ep3_master": 4.0,
    "ep3": 7.0,
    "ep5": 7,
    "star_rank5": 3,
    "ep7": 39,
    "star_rank7": 2,
    "ep8": 8,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "YOON MIN",
    "nickname": "YOON MIN",
    "subheading": "I will do my best to shine brightly every moment, without any regrets!",
    "birthday": "2000.12.22",
    "height": 170.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d047baf74224bf4de7adc?hl=en",
    "imagefile": "44.jpg",
    "agency": "howtouse",
    "hobby": "Composing original songs, collecting figures",
    "specialty": "Imitating Donald Duck, singing a song in freestyle, \nmaking scrambled eggs",
    "name1": "Yoon Min",
    "kc_name": "윤민",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 32.0,
    "ep2": 38.0,
    "star_rank2": 3.0,
    "ep3_master": 13.0,
    "ep3": 49.0,
    "ep5": 48,
    "star_rank5": 2,
    "ep7": 8,
    "star_rank7": 3,
    "ep8": 30,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "YUMEKI",
    "nickname": "YUMEKI",
    "subheading": "This is my first and final challenge—please stay by my side until the end! Let’s go!",
    "birthday": "1999.11.12",
    "height": 172.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d00edaf74224bf4de7adb?hl=en",
    "imagefile": "45.jpg",
    "agency": "GRIGO ENTERTAINMENT",
    "hobby": "Shopping for clothes, watching Korean dramas, mukbang",
    "specialty": "Flexibility, controlling facial expressions while dancing",
    "name1": "Yumeki",
    "kc_name": "유메키",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 10.0,
    "ep2": 11.0,
    "star_rank2": 3.0,
    "ep3_master": 1.0,
    "ep3": 14.0,
    "ep5": 17,
    "star_rank5": 3,
    "ep7": 48,
    "star_rank7": 2,
    "ep8": 22,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "ZHANG JIA HAO",
    "nickname": "ZHANG JIA HAO",
    "subheading": "Please look forward to me! I will do my very best with no regrets until the end!",
    "birthday": "2002.07.07",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6841456874366b31a1c003ad?hl=en",
    "imagefile": "46.jpg",
    "agency": "NOUER ENTERTAINMENT",
    "hobby": "Shopping, fashion styling, basketball",
    "specialty": "Continuously spinning a basketball",
    "name1": "Zhang Jia hao",
    "kc_name": "张家豪",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 12.0,
    "ep2": 8.0,
    "star_rank2": 3.0,
    "ep3_master": 8.0,
    "ep3": 16.0,
    "ep5": 18,
    "star_rank5": 3,
    "ep7": 28,
    "star_rank7": 3,
    "ep8": 19,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "ZHAO GUANG XU",
    "nickname": "ZHAO GUANG XU",
    "subheading": "Start your journey toward your dream from zero.",
    "birthday": "2003.11.03",
    "height": 183.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684144a000163a1e33dac0f4?hl=en",
    "imagefile": "47.jpg",
    "agency": "IX ENTERTAINMENT",
    "hobby": "Dancing, playing games",
    "specialty": "Dancing",
    "name1": "Zhao Guang xu",
    "kc_name": "赵光旭",
    "group": "C",
    "star_rank1": 1.0,
    "ep1": 9.0,
    "ep2": 18.0,
    "star_rank2": 1.0,
    "ep3_master": 64.0,
    "ep3": 28.0,
    "ep5": 34,
    "star_rank5": 2,
    "ep7": 41,
    "star_rank7": 2,
    "ep8": 34,
    "star_rank8": 2,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 8
  },
  {
    "name": "ZHOU AN XIN",
    "nickname": "ZHOU AN XIN",
    "subheading": "I will do my very best in this program, show you everything I have, and leave no regrets",
    "birthday": "2006.12.25",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684145ec706fa26293682519?hl=en",
    "imagefile": "48.jpg",
    "agency": "NOUER ENTERTAINMENT",
    "hobby": "Basketball, watching cooking videos, shopping and fashion styling, watching animation",
    "specialty": "Rapping in three languages",
    "name1": "Zhou An xin",
    "kc_name": "周安信",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 1.0,
    "ep2": 1.0,
    "star_rank2": 3.0,
    "ep3_master": 3.0,
    "ep3": 2.0,
    "ep5": 2,
    "star_rank5": 3,
    "ep7": 15,
    "star_rank7": 3,
    "ep8": 2,
    "star_rank8": 3,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": -1
  },
  {
    "name": "ANDREW",
    "nickname": "ANDREW",
    "subheading": "I will do my best to create music that touches the listener’s heart.",
    "birthday": "2003.12.19",
    "height": 176.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6836c30108c3cc45013ac3ae?hl=en",
    "imagefile": "49.jpg",
    "agency": "Bill ENTERTAINMENT",
    "hobby": "Shopping at vintage shops, finding and visiting taco shops or famous restaurants, playing basketball, meditating, reading books",
    "specialty": "Topline songwriting, writing lyrics",
    "name1": "Andrew",
    "kc_name": "앤드류",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 40.0,
    "ep2": 40.0,
    "star_rank2": 2.0,
    "ep3_master": 27.0,
    "ep3": 55.0,
    "ep5": 54,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "AOSHI",
    "nickname": "AOSHI",
    "subheading": "I will capture the hearts of the Star Creators with my unique style and make it to the end!",
    "birthday": "2006.10.09",
    "height": 171.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6836ceea408f877d1bddd4d6?hl=en",
    "imagefile": "50.jpg",
    "agency": "BIG PLANET MADE ENTERTAINMENT",
    "hobby": "Exercising, imagining pleasant moments, enjoying tea ceremonies, watching horror movies, finding delicious bakeries",
    "specialty": "Playing handball, using a whistle, doing leg splits, smiling often, taking selfies, eating well",
    "name1": "Aoshi",
    "kc_name": "아오시",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 35.0,
    "ep2": 44.0,
    "star_rank2": 2.0,
    "ep3_master": 42.0,
    "ep3": 60.0,
    "ep5": 67,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "BANG JUN HYUK",
    "nickname": "BANG JUN HYUK",
    "subheading": "I’m ready to make a lasting impression—straight to your heart!",
    "birthday": "2004.12.19",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683972acb6da843399c19e22?hl=en",
    "imagefile": "51.jpg",
    "agency": "TOP MEDIA",
    "hobby": "Playing Tekken, composing music",
    "specialty": "Music production",
    "name1": "Bang Jun hyuk",
    "kc_name": "방준혁",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 21.0,
    "ep2": 27.0,
    "star_rank2": 1.0,
    "ep3_master": 79.0,
    "ep3": 44.0,
    "ep5": 50,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "BIAN SHI YU",
    "nickname": "BIAN SHI YU",
    "subheading": "If you get up one more time than you fall, that’s what success is!",
    "birthday": "2006. 06. 21",
    "height": 172.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68411bd95a617c7dfa2bb1c1?hl=en",
    "imagefile": "52.jpg",
    "agency": "TOPCLASS ENTERTAINMENT",
    "hobby": "Badminton, role-playing mystery game, mystery game (Pelican soup riddle)",
    "specialty": "Moving eyebrows like waves, lifting tongue",
    "name1": "Bian Shi yu",
    "kc_name": "卞士宇",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 41.0,
    "ep2": 38.0,
    "star_rank2": 2.0,
    "ep3_master": 38.0,
    "ep3": 62.0,
    "ep5": 64,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "CHRISEN YANG",
    "nickname": "CHRISEN YANG",
    "subheading": "With my unique charisma, I will make sure you remember the name ‘CHRISEN YANG'.",
    "birthday": "2004.12.29",
    "height": 180.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6841484419ba4629c4a692ab?hl=en",
    "imagefile": "53.jpg",
    "agency": "RYCE Entertainment",
    "hobby": "Singing, dancing, skiing",
    "specialty": "Choreographing",
    "name1": "Chrisen Yang",
    "kc_name": "克里森 杨",
    "group": "C",
    "star_rank1": 1.0,
    "ep1": 49.0,
    "ep2": 51.0,
    "star_rank2": 1.0,
    "ep3_master": 74.0,
    "ep3": 68.0,
    "ep5": 78,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "DONG JING KUN",
    "nickname": "DONG JING KUN",
    "subheading": "Without rushing, I’ve calmly prepared everything, so now all that’s left is to reach the top",
    "birthday": "2005.09.29",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6840ff13746e21370e0a9686?hl=en",
    "imagefile": "54.jpg",
    "agency": "Dragon Team Film and Television Culture",
    "hobby": "Dancing",
    "specialty": "Taekwondo",
    "name1": "Dong Jing kun",
    "kc_name": "董靖坤",
    "group": "C",
    "star_rank1": 3.0,
    "ep1": 56.0,
    "ep2": 33.0,
    "star_rank2": 1.0,
    "ep3_master": 76.0,
    "ep3": 63.0,
    "ep5": 72,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "GUO ZHEN",
    "nickname": "GUO ZHEN",
    "subheading": "Overcome hardships and become the best version of yourself!",
    "birthday": "2002.08.11",
    "height": 183.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6840f6a757c45f3f52065f98?hl=en",
    "imagefile": "55.jpg",
    "agency": "Giant Entertainment Music",
    "hobby": "Cooking, billiards",
    "specialty": "Solo dance",
    "name1": "Guo Zhen",
    "kc_name": "郭震",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 24.0,
    "ep2": 28.0,
    "star_rank2": 1.0,
    "ep3_master": 56.0,
    "ep3": 52.0,
    "ep5": 52,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "HAM HYUN SEO",
    "nickname": "HAM HYUN SEO",
    "subheading": "I’ll give my all in every moment and live each day without regret",
    "birthday": "2007.01.14",
    "height": 185.5,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d40a18938582ad19843a9?hl=en",
    "imagefile": "56.jpg",
    "agency": "nCH ENTERTAINMENT",
    "hobby": "Drawing, swimming, exercising",
    "specialty": "Venom voice",
    "name1": "Ham Hyun seo",
    "kc_name": "함현서",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 68.0,
    "ep2": 67.0,
    "star_rank2": 1.0,
    "ep3_master": 51.0,
    "ep3": 80.0,
    "ep5": 60,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "HONG ZHI HAN",
    "nickname": "HONG ZHI HAN",
    "subheading": "I will show you HONG ZHI HAN shining on stage!",
    "birthday": "2004.06.17",
    "height": 173.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684149d1fedad651c74a99aa?hl=en",
    "imagefile": "57.jpg",
    "agency": "Individual",
    "hobby": "Composing, traveling, cooking, swimming",
    "specialty": "Infinite hiccuping, bending fingers",
    "name1": "Hong Zhi han",
    "kc_name": "洪智函",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 61.0,
    "ep2": 66.0,
    "star_rank2": 3.0,
    "ep3_master": 21.0,
    "ep3": 74.0,
    "ep5": 70,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "HONG ZIH HAO",
    "nickname": "HONG ZIH HAO",
    "subheading": "As long as you have faith, there’s nothing to worry about!",
    "birthday": "2005.04.11",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684149b2f6324a677827b144?hl=en",
    "imagefile": "58.jpg",
    "agency": "TEN ENTERTAINMENT",
    "hobby": "Drawing, playing games, learning languages, watching horror movies",
    "specialty": "Drawing illustrations, acting, mimicking, laughter",
    "name1": "Hong Zih hao",
    "kc_name": "洪子皓",
    "group": "C",
    "star_rank1": 1.0,
    "ep1": 18.0,
    "ep2": 23.0,
    "star_rank2": 1.0,
    "ep3_master": 71.0,
    "ep3": 43.0,
    "ep5": 56,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "JANG TAE YOON",
    "nickname": "JANG TAE YOON",
    "subheading": "I’ll train hard to never lose in dance to anyone!",
    "birthday": "2006.07.29",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d2c8fcea3fa27508ca264?hl=en",
    "imagefile": "59.jpg",
    "agency": "iNKODE ENTERTAINMENT",
    "hobby": "Rewatching movies previously enjoyed",
    "specialty": "Freestyle dance",
    "name1": "Jang Tae yoon",
    "kc_name": "장태윤",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 67.0,
    "ep2": 62.0,
    "star_rank2": 2.0,
    "ep3_master": 32.0,
    "ep3": 72.0,
    "ep5": 80,
    "star_rank5": -1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "JIANG FAN",
    "nickname": "JIANG FAN",
    "subheading": "To become a better version of myself, hard work will always be rewarded, Passion!!!",
    "birthday": "2005. 05. 19",
    "height": 174.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68414692d44b3c677aa45cdf?hl=en",
    "imagefile": "60.jpg",
    "agency": "TOPCLASS ENTERTAINMENT",
    "hobby": "Cooking, cycling, camping, board games",
    "specialty": "Freestyle dance, choreographing",
    "name1": "Jiang Fan",
    "kc_name": "姜帆",
    "group": "C",
    "star_rank1": 1.0,
    "ep1": 38.0,
    "ep2": 37.0,
    "star_rank2": 2.0,
    "ep3_master": 36.0,
    "ep3": 56.0,
    "ep5": 63,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KIM DANIEL",
    "nickname": "KIM DANIEL",
    "subheading": "I’ll do my best—as far as destiny allows.",
    "birthday": "2009.03.05",
    "height": 188.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837e1270eb5b81bbc4b4cb4?hl=en",
    "imagefile": "61.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Walking while listening to music, doing light exercise",
    "specialty": "Eating three bowls of double portions of Jajangmyeon, \nfalling asleep within three minutes",
    "name1": "Kim Daniel",
    "kc_name": "김다니엘",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 23.0,
    "ep2": 32.0,
    "star_rank2": 1.0,
    "ep3_master": 67.0,
    "ep3": 53.0,
    "ep5": 59,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KIM DONG HYUN A",
    "nickname": "KIM DONG HYUN A",
    "subheading": "All-rounder? I’ll prove it on stage, not with words.",
    "birthday": "2003.10.23",
    "height": 174.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837b73db12f8f5047c2d8fc?hl=en",
    "imagefile": "62.jpg",
    "agency": "Individual",
    "hobby": "Walking, reading, swimming, going on impromptu solo trips",
    "specialty": "Modern dance",
    "name1": "Kim Dong hyun A",
    "kc_name": "김동현A",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 61.0,
    "ep2": 64.0,
    "star_rank2": 1.0,
    "ep3_master": 65.0,
    "ep3": 75.0,
    "ep5": 66,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KIM DONG HYUN B",
    "nickname": "KIM DONG HYUN B",
    "subheading": "I’m here to become number one.",
    "birthday": "2008.12.14",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837b8e9cbda8e7e840d2707?hl=en",
    "imagefile": "63.jpg",
    "agency": "P NATION",
    "hobby": "Playing basketball, walking, composing music, watching variety shows",
    "specialty": "Exercising, ventriloquism rapping, songwriting, hip-hop",
    "name1": "Kim Dong hyun B",
    "kc_name": "김동현B",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 62.0,
    "ep2": 60.0,
    "star_rank2": 1.0,
    "ep3_master": 54.0,
    "ep3": 71.0,
    "ep5": 53,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KIM HYEON SEO",
    "nickname": "KIM HYEON SEO",
    "subheading": "I’ll give everything I have at every moment.",
    "birthday": "2007.07.31",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837c802fc84b02b6541e05c?hl=en",
    "imagefile": "64.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Using imagination, reading, drawing, playing the piano",
    "specialty": "Speaking foreign languages, swimming",
    "name1": "Kim Hyeon seo",
    "kc_name": "김현서",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 63.0,
    "ep2": 66.0,
    "star_rank2": 1.0,
    "ep3_master": 73.0,
    "ep3": 78.0,
    "ep5": 75,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KIM YOUNG JUN",
    "nickname": "KIM YOUNG JUN",
    "subheading": "Dazzling KIM YOUNG JUN! I’ll never back down and always smile!!!!!!!!!!!!!!!!!",
    "birthday": "2010.01.29",
    "height": 181.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837bab1d18a13793c4ad046?hl=en",
    "imagefile": "65.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Collecting seals included in character bread packaging, \neating jellies and evaluating their taste ☆☆☆☆☆",
    "specialty": "Laughter autoplay human (Too much laughter! Be careful of the noise!)",
    "name1": "Kim Young jun",
    "kc_name": "김영준",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 58.0,
    "ep2": 59.0,
    "star_rank2": 1.0,
    "ep3_master": 52.0,
    "ep3": 79.0,
    "ep5": 73,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "KO MING CHIEH",
    "nickname": "KO MING CHIEH",
    "subheading": "I am not afraid of hardship and am someone who can endure and persevere I will definitely debut on BOYS II PLANET and become the brightest star",
    "birthday": "2007.09.11",
    "height": 170.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68414822c2152d4c695a8006?hl=en",
    "imagefile": "66.jpg",
    "agency": "WAKEONE",
    "hobby": "Drawing, playing guitar, singing, sports",
    "specialty": "Dancing, piano, drawing",
    "name1": "Ko Ming chieh",
    "kc_name": "柯茗傑",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 58.0,
    "ep2": 59.0,
    "star_rank2": 1.0,
    "ep3_master": 57.0,
    "ep3": 77.0,
    "ep5": 76,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "LEE DONG HEON",
    "nickname": "LEE DONG HEON",
    "subheading": "I’ll show you what it means to truly do your best!",
    "birthday": "1995.08.04",
    "height": 179.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d0647cea3fa27508ca263?hl=en",
    "imagefile": "67.jpg",
    "agency": "JELLYFISH ENTERTAINMENT",
    "hobby": "Watching dramas",
    "specialty": "Composing music, playing piano",
    "name1": "Lee Dong heon",
    "kc_name": "이동헌",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 29.0,
    "ep2": 28.0,
    "star_rank2": 2.0,
    "ep3_master": 37.0,
    "ep3": 45.0,
    "ep5": 49,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "LEE SEUNG BAEK",
    "nickname": "LEE SEUNG BAEK",
    "subheading": "Victory! 100%! I will work hard to come out on top!",
    "birthday": "2010.09.29",
    "height": 176.7,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d0c058938582ad19843a7?hl=en",
    "imagefile": "68.jpg",
    "agency": "Woollim ENTERTAINMENT",
    "hobby": "Opening the refrigerator, exercising, imagining, drawing",
    "specialty": "Dancing, playing the hand recorder",
    "name1": "Lee Seung baek",
    "kc_name": "이승백",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 49.0,
    "ep2": 54.0,
    "star_rank2": 1.0,
    "ep3_master": 69.0,
    "ep3": 73.0,
    "ep5": 79,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "MUHN WON JUN",
    "nickname": "MUHN WON JUN",
    "subheading": "I will enjoy this journey.",
    "birthday": "2005.10.26",
    "height": 180.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837e728c097b8004d469130?hl=en",
    "imagefile": "69.jpg",
    "agency": "CJes Studios",
    "hobby": "Playing basketball, skateboarding, bowling, browsing clothes",
    "specialty": "Performing in the circus, playing violin, running marathons",
    "name1": "Muhn Won jun",
    "kc_name": "문원준",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 43.0,
    "ep2": 51.0,
    "star_rank2": 2.0,
    "ep3_master": 29.0,
    "ep3": 69.0,
    "ep5": 62,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "NOH HUI JUN",
    "nickname": "NOH HUI JUN",
    "subheading": "You’ll be captivated by me. I will deliver perfection in every aspect, from singing to dancing!!",
    "birthday": "2003.10.07",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d4c3daba63741258d47f0?hl=en",
    "imagefile": "70.jpg",
    "agency": "TOP MEDIA",
    "hobby": "Listening to songs, collecting vinyl records, singing,watching dramas and movies, playing games",
    "specialty": "Singing, dancing",
    "name1": "Noh Hui jun",
    "kc_name": "노휘준",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 46.0,
    "ep2": 46.0,
    "star_rank2": 3.0,
    "ep3_master": 24.0,
    "ep3": 67.0,
    "ep5": 77,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "OH JUN HO",
    "nickname": "OH JUN HO",
    "subheading": "Watch out—you’ll be falling for me before you know it.",
    "birthday": "2004.10.19",
    "height": 178.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683cfc586407a7122301f975?hl=en",
    "imagefile": "71.jpg",
    "agency": "WITHUS ENTERTAINMENT",
    "hobby": "Touring bakeries, drawing, watching movies",
    "specialty": "Math, electric guitar, rugby",
    "name1": "Oh Jun ho",
    "kc_name": "오준호",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 65.0,
    "ep2": 65.0,
    "star_rank2": 2.0,
    "ep3_master": 48.0,
    "ep3": 70.0,
    "ep5": 61,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "REEONN",
    "nickname": "REEONN",
    "subheading": "I will shine brighter than anyone else on stage and work hard!",
    "birthday": "2007.01.22",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d4d0faba63741258d47f1?hl=en",
    "imagefile": "72.jpg",
    "agency": "WAKEONE",
    "hobby": "Playing soccer and tennis, watching movies",
    "specialty": "Playing LumiCube, playing the ukulele",
    "name1": "Reeonn",
    "kc_name": "리온",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 50.0,
    "ep2": 45.0,
    "star_rank2": 2.0,
    "ep3_master": 35.0,
    "ep3": 64.0,
    "ep5": 58,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "RENSHO",
    "nickname": "RENSHO",
    "subheading": "Hi, it’s RENSHO! Have you picked your favorite yet? If you already have, please change it to me~!",
    "birthday": "2007.12.19",
    "height": 176.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6837e387b21a33083c9b6186?hl=en",
    "imagefile": "73.jpg",
    "agency": "IST ENTERTAINMENT",
    "hobby": "Sleeping, traveling, eating, watching videos, playing games",
    "specialty": "Making shoulder blade sounds, cleaning fish, practicing judo",
    "name1": "Rensho",
    "kc_name": "렌쇼",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 44.0,
    "ep2": 36.0,
    "star_rank2": 1.0,
    "ep3_master": 75.0,
    "ep3": 57.0,
    "ep5": 68,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "SHO",
    "nickname": "SHO",
    "subheading": "I’ll make your summer cooler with my refreshing energy!!",
    "birthday": "2005.12.20",
    "height": 167.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68397b2862e19e064eec8505?hl=en",
    "imagefile": "74.jpg",
    "agency": "nCH ENTERTAINMENT",
    "hobby": "Playing the piano, guitar, and ukulele,baking, cycling",
    "specialty": "Speaking Korean, playing musical instruments (kendama, piano, guitar, ukulele)",
    "name1": "Sho",
    "kc_name": "쇼우",
    "group": "K",
    "star_rank1": 1.0,
    "ep1": 37.0,
    "ep2": 49.0,
    "star_rank2": 1.0,
    "ep3_master": 77.0,
    "ep3": 66.0,
    "ep5": 74,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "SONG MIN JAE",
    "nickname": "SONG MIN JAE",
    "subheading": "Let yourself be completely immersed in my endless charm—open your eyes and ears, and enjoy the show!",
    "birthday": "2003.08.23",
    "height": 180.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/6839780e2df59069b98136f1?hl=en",
    "imagefile": "75.jpg",
    "agency": "TOP MEDIA",
    "hobby": "Watching animations, painting, cooking, baking",
    "specialty": "Being versatile",
    "name1": "Song Min jae",
    "kc_name": "송민재",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 30.0,
    "ep2": 37.0,
    "star_rank2": 1.0,
    "ep3_master": 78.0,
    "ep3": 58.0,
    "ep5": 55,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "TAIGA",
    "nickname": "TAIGA",
    "subheading": "With maximum confidence, I will seize my debut!",
    "birthday": "2005.05.17",
    "height": 180.2,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/68414891b3c476154e980aff?hl=en",
    "imagefile": "76.jpg",
    "agency": "IX ENTERTAINMENT",
    "hobby": "Watching animation, eating delicious food, rapping, dancing",
    "specialty": "Lyric writing, choreographing",
    "name1": "Taiga",
    "kc_name": "타이가",
    "group": "C",
    "star_rank1": 1.0,
    "ep1": 42.0,
    "ep2": 36.0,
    "star_rank2": 2.0,
    "ep3_master": 46.0,
    "ep3": 59.0,
    "ep5": 65,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "YANG DA WIT",
    "nickname": "YANG DA WIT",
    "subheading": "I’ll do my best so I have no regrets",
    "birthday": "2008.03.10",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683980cce0def45b55c41589?hl=en",
    "imagefile": "77.jpg",
    "agency": "RBW",
    "hobby": "Taking walks, drawing, binge-watching dramas",
    "specialty": "Dancing, drawing",
    "name1": "Yang Da wit",
    "kc_name": "양다윗",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 55.0,
    "ep2": 63.0,
    "star_rank2": 1.0,
    "ep3_master": 72.0,
    "ep3": 76.0,
    "ep5": 71,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "YANG HEUI CHAN",
    "nickname": "YANG HEUI CHAN",
    "subheading": "Believe in me and follow my lead—I’ll make you smile.",
    "birthday": "1999.07.31",
    "height": 175.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683cf8f7b6da843399c19e23?hl=en",
    "imagefile": "78.jpg",
    "agency": "BRAVE ENTERTAINMENT",
    "hobby": "Dancing, exercising (workout and soccer),finding dance videos, doing threadwork, reading books while doing the splits",
    "specialty": "Creating choreography, deboning chicken, responding with positive words, imitating animals, doing 70 push-ups in 1 minute, making people happy",
    "name1": "Yang Heui chan",
    "kc_name": "양희찬",
    "group": "K",
    "star_rank1": 3.0,
    "ep1": 52.0,
    "ep2": 50.0,
    "star_rank2": 2.0,
    "ep3_master": 41.0,
    "ep3": 61.0,
    "ep5": 57,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "YUSEN",
    "nickname": "YUSEN",
    "subheading": "I pour my heart and soul into this opportunity.",
    "birthday": "2008.05.05",
    "height": 176.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/683d020c8938582ad19843a6?hl=en",
    "imagefile": "79.jpg",
    "agency": "P NATION",
    "hobby": "Cooking, playing volleyball, shopping, playing games",
    "specialty": "Doing leg splits, performing freestyle dance",
    "name1": "Yusen",
    "kc_name": "유센",
    "group": "K",
    "star_rank1": 2.0,
    "ep1": 48.0,
    "ep2": 52.0,
    "star_rank2": 2.0,
    "ep3_master": 43.0,
    "ep3": 65.0,
    "ep5": 69,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  },
  {
    "name": "ZHANG SHUN YU",
    "nickname": "ZHANG SHUN YU",
    "subheading": "With endless passion, let’s head toward the mountains and the sea together!",
    "birthday": "2010.03.25",
    "height": 173.0,
    "profileurl": "https://share.mnetplus.world/boys2planet/participants/684144cac2152d4c695a8005?hl=en",
    "imagefile": "80.jpg",
    "agency": "Dragon Team Film and Television Culture",
    "hobby": "Dancing, basketball",
    "specialty": "Taekwondo, dancing",
    "name1": "Zhang Shun yu",
    "kc_name": "张舜禹",
    "group": "C",
    "star_rank1": 2.0,
    "ep1": 33.0,
    "ep2": 27.0,
    "star_rank2": 2.0,
    "ep3_master": 31.0,
    "ep3": 48.0,
    "ep5": 51,
    "star_rank5": 1,
    "ep7":-1,
    "star_rank7": -1,
    "ep8": -1,
    "star_rank8": -1,
    "ep9": -1,
    "ep11": -1,
    "ep12": -1,
    "eliminated_ep": 5
  }
]

